### ISSUE TITLE
part of page font is not correct & Horizontal scrollbar

### ISSUE THREAD

**Issue by amirghazi87** [Novelvo/fa.novelvo.ir#1]
**Screen Shot of problem**

![Screenshot from 2021-09-01 00-56-20](https://user-images.githubusercontent.com/72940447/131571164-c17e015b-0bbb-4c72-a029-bd49e6c7d257.png)

**Browser Information**
Linux Mint 20
Google Chrome 92.0
**Problem Description**
I don't know why but you set the font of this part of page in a part of `light` CSS file to English fonts
![Screenshot from 2021-09-01 00-55-53](https://user-images.githubusercontent.com/72940447/131571523-05894e41-9b2a-4441-8c27-f0e96156380e.png)
<hr/>

page without any zoom have a horizontal scrollbar and I think it's not good when the content of the page doesn't need and horizontal scrollbar

**Comment by BlackIQ** [comment]
Hi again,

Yeah agreed. Persian version is still on working and didn't have time to fix them.
Will do it today.

Anyway, thanks for letting me know.

May the force be with you.
Amirhossein.

**Comment by BlackIQ** [comment]
Font fixed. But can you talk about **Horizontal scroollbar** little more?

**Comment by amirghazi87** [comment]
> Font fixed. But can you talk about **Horizontal scrollbar** little more?

yes, I test the site in firefox and it's ok
but in google chrome, it's like this screenshot
![Screenshot from 2021-09-01 14-15-37](https://user-images.githubusercontent.com/72940447/131650155-194fc754-7929-4846-a40d-80939bfaa489.png)
can be correct with ` overflow-x: hidden; ` for `body` in CSS file

**Comment by BlackIQ** [comment]
I'll do it now.
Tnx.
